### PR TITLE
Fix exponential cone in conic tutorial

### LINKED ISSUE #50: Exponential cone for entropy example is wrong
First thank a lot for putting these examples together!

The entropy maximization example under "Conic Programming" contains a bug. The correct exponential cone for this example is
(t,x,1)∈Kexp
instead of
(1,x,t)∈Kexp .

Hence the constraint should be
```Julia
@constraint(model, con[i = 1:n], [t[i]], x[i], 1] in MOI.ExponentialCone())
```

### PR DESCRIPTION
**Pull request by frapac**
For some reason, MOI does not follow the same convention as Mosek. 
Should resolve #50 

This PR fixes some typos as well.

### CODE REVIEW

File: script/optimization_concepts/conic_programming.jl [hunk 1]
```diff
@@ -132,12 +132,12 @@ optimize!(model)
 
 #+
 
-e1 = [1, zeros(10)...]
+e1 = [1.0, zeros(10)...]
```
Comment (matbesancon) [inline script/optimization_concepts/conic_programming.jl]: The int -> float conversions are not necessary in that case, since the zeros(10) will promote everything. Same below since these are constraint specifications ints are converted

File: script/optimization_concepts/conic_programming.jl [hunk 2]
```diff
@@ -220,10 +220,10 @@ model = Model(optimizer_with_attributes(ECOS.Optimizer, "printlevel" => 0))
...
 @variable(model, x[1:n])
 @objective(model, Max, sum(t))
-@constraint(model, sum(x) == 1)
+@constraint(model, sum(x) == 1.0)
 @constraint(model, A * x .<= b )
 # Cannot use the exponential cone directly in JuMP, hence we use MOI to specify the set.
-@constraint(model, con[i = 1:n], [1, x[i], t[i]] in MOI.ExponentialCone())
+@constraint(model, con[i = 1:n], [t[i], x[i], 1.0] in MOI.ExponentialCone())
 
 optimize!(model);
```
Comment (matbesancon) [inline script/optimization_concepts/conic_programming.jl:229]: Maybe we should add a test on the objective value to verify the optimality of the solution found

File: script/optimization_concepts/conic_programming.jl (hunk 1 above)
Comment (frapac) [reply script/optimization_concepts/conic_programming.jl]: You are right, indeed. I will update the PR accordingly.

File: script/optimization_concepts/conic_programming.jl (hunk 2 above)
Comment (frapac) [reply script/optimization_concepts/conic_programming.jl:229]: That makes sense.

Comment (frapac) [reply script/optimization_concepts/conic_programming.jl:229]: I add new test only for the different conic formulations. But that would be great to refact the tests overall in my opinion.

Comment (matbesancon) [reply script/optimization_concepts/conic_programming.jl:229]: you mean in the file or in the tutorials overall?

Comment (frapac) [reply script/optimization_concepts/conic_programming.jl:229]: in the tutorial overall

Comment (frapac) [reply script/optimization_concepts/conic_programming.jl:229]: Just catch a typo in the tests for `SecondOrderCone` formulation (my bad). I will fix that ASAP.
